language: android

jdk: oraclejdk8

env:
    global:
        - ANDROID_TARGET=android-15
        - ANDROID_ABI=armeabi-v7a
        - secure: "qj83DQabUBGt5RG30pnY4YPsCvYQrHAR8UfOajMeRTXwqL17F0w16OLfKBFJV0IjvsjdH0WdWMiPD1Wrmt+E3uw+ep0US/I4zj2+9VLc/q4fv1KWD5C+n49asB/szyP7rVv2PWxmFCgi2gzYBfss+wdPaSt2RPmfU8ws2jG92NOAYnYCP9zBy2GSFWYWfznwEAch7X+WU9ALUm48rfcPX8o+N7ziM89NzMfCCyY9VTvXmWN/ICwitYzaYIZ4bNsIRt5heOO3K9udOyY+qkVPhOWyBDe2p7FuIgAgWK81pyEt7LqoEF9KylCkBL2l/FKiSMEL/XD7BvWnU0gy8S/IMKVIx1ZV9e6uh+yY6AtTcUaF9G3w1hGsWRUCSN3UXK9vz0F3+Kdb8ddz4izzxegOim9mLdtCrIeyL51SVZzNVUe6ttoNk/M+BWDrYcwtuh/BNo/RwV5HfW5ZRz7L6PgIX2EdErBXDoX16ejS8k5X8XeszmJZFXzm9tbpxZMC5NpbMLqwYNxSuv8sEVr4rItB1cT543HNLG6zLUUy5A+Y5uiSUT0Qlf6FwOTEkV3IvQ7MZrJ4+D9ynDA0l6XJZzyMLDGJyTmHIQbEmd0G//dyeg/uUtb6kH8ikT+hac3ahvLalKM5tqfMAbu8rGfmGc4LpGPsO7btJ+mphwLl2Nai7FY="
        - secure: "okpM5WES6+tzHbSLeYvldmLQcc9BaqfxPHI0usBJwhCzE3BGzK+cFdbQviCkU0oCBHTLTrCF+BZrlZZbcqNPC1odEYHI4nolq2EBkKVRpUrVCeIK99Jp9j/cX80ATfWLO0FZNhZn5bTFjZWfNxMRAypul+xHcnXm57BvcabwyZHBb6wUd8oatrxSL3GqquZ/7MjR1P0P/5QPkVkAvL7Fa63ILgrH0pKl6gCC0VVMz23Y+letEueUBeJi8Oi6KPn4wzdLFodUCcIRMyfnf3mPdieGnmcY9W/icobkUGZdTZeSjINGjDVQ8ZS8bxbAKgv0A2TZG46yOttc5l963sIK707hpUTDviNnEk3uMC4kHXEmCuz+m25SJrBLbYrm/Q9vp+2VqfW8tnE3Z9KKor8cj2avndTW0amQhV46qt+hkfJyek482JPSuw0nklCJyCszlbmtDwbdpyxrKeQ+tulNjY4UeDB/XD/pk2lo10bCiWgl/afV0Pp4HYFuW3kyfV/ElgmMjYYT/YF3wMm4PRjfd9NF/hPKHN1Y33hSuii4NY6AsDEgghCKGW5ChKvrBLsaOaszzmzwGEqfCDNASSt/0lMhy3wP4PSCsvF4ipHJW2kFwGgIRv3LhOSR5XbP3jvKySzapK29V5HpFoJ8EzxxnuRB9rN9VHcgkwr/gyK/vnM="

android:
    components:
        - tools
        - build-tools-25.0.2
        - platform-tools
        - android-22
        - android-25
        - extra-android-m2repository
        - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    script:
        - ./gradlew build jacocoTestReport assembleAndroidTest
        - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
        - emulator -avd test -no-skin -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
        - ./gradlew connectedCheck
    after_success:
        - bash <(curl -s https://codecov.io/bash) 
