language: android

jdk: oraclejdk8

env:
    global:
        - ANDROID_TARGET=android-22
        - ANDROID_ABI=armeabi-v7a
     
android:
    components:
        - tools
        - build-tools-26.0.2
        - platform-tools
        - android-22
        - android-25
        - android-26
        - extra-android-m2repository
        - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'

before_install:     
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-27" 

script:
    - ./gradlew build assembleAndroidTest
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-window &
    - android-wait-for-emulator
    - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
    - ./gradlew connectedCheck
